language: ruby
rvm:
  - 2.4.2
before_script:
  - psql -c 'create database dc_timetracker_test;' -U postgres
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare --trace
script:
  - bundle exec rubocop
  - bundle exec rspec
